# Ana başlık tek diyez (#) (Hücreyi seçerek JupyterLab görev çubuğunun sonunda bulunan alanda Markdown'ı seçmeliyiz.)

## Alt başlık iki diyez (##) (Hücreyi seçerek JupyterLab görev çubuğunun sonunda bulunan alanda Markdown'ı seçmeliyiz.)

_italik_ (_ xxx _ formatında yazarak italik formatta yazı yazabiliriz.)


**kalın** (* * xxx * *) formatında yazarak kalın formatta yazı yazabiliriz.)

# Neden Numpy ?

In [2]:
a = [1,2,3]
b = [4,5,6]
a
b

[4, 5, 6]

Hücreleme mantığından dolayı en alt satırda hangi eleman varsa JupyterLav çalıştırmak için onu seçer. a ve b'nin her ikisini de çalıştırmak istiyorsak ayrı ayrı hücrelerde çağırmalıyız.

In [3]:
a = [1,2,3]
b = [4,5,6]

In [4]:
ab = []
for i in range(0, len(a)):
    ab.append(a[i] * b[i])
ab

[4, 10, 18]

Yukarıdaki kod satırları numpy kütüphanesi kullanmadan iki vektörü çarpmak için gerekli olan işlemlerin bütünüdür, peki numpy ile ne yapmak gerekiyor.

In [1]:
import numpy as np #numpy kütüphanesini kullanmak için import ediyoruz.

In [7]:
a = np.array([1,2,3])
b = np.array([4,5,6])
#numpy array'leri oluşturmuş olduk.

In [8]:
a * b

array([ 4, 10, 18])

numpy'ı import ettikten sonra tek bir satır kod yazarak aynı sonucu alabiliyoruz.

Numpy ile daha üst seviyeden daha az efor ile daha fazla iş yapılabilir.

Veri saklama anlamında da numpy çok daha işimize yarıyor; liste ile farkına bakacak olursak 4 elemanlı bir liste ve np.array düşünelim. listede her bir eleman için
ayrı ayrı tip bilgisi tutulacaktır fakat np.array kullanarak bu sayıyı 1'e indirebiliyoruz.

In [2]:
np.array([1, 2, 3, 4.55], dtype="int")

array([1, 2, 3, 4])

In [3]:
np.array([1, 2, 3, 4.55])

array([1.  , 2.  , 3.  , 4.55])

Eğer ki array'i yazdıktan sonra dtype belirtmemiş olsaydık array'in tipi otomatik olarak float'a dönüşecekti fakat bazı durumlarda bunu istemeyebiliriz bu gibi durumlar için de array'i
oluştururken "dtype" özelliğinden faydanalarak içerisindeki verilerin hangi tipte olması gerektiğini belirleyebiliriz.

In [5]:
np.zeros(10) #0'lardan array oluşturur. #int'e çevirmek için dtype ekleyebilirsiniz.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones((3,5), dtype = int) #1'lerden array oluşturur.

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
np.full((2,3), 5, dtype = int) #Belirttiğimiz sayıya göre array oluşturur.

array([[5, 5, 5],
       [5, 5, 5]])

In [11]:
np.arange(0, 30, 5) #Belirtilen aralıkta 5'er artarak vektör üretir.

array([ 0,  5, 10, 15, 20, 25])

In [12]:
np.linspace(0, 1, 5) #0 ile 1 arasında eşit aralıklarda 5 adet eleman olacak şekilde vektör üretir.

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
np.random.normal(5, 3, (2,5)) #(2,5) lik ortalaması 5, standart sapması 3 olacak şekilde matris üretir. 

array([[ 6.56912866,  5.1207907 ,  5.4263912 , 11.55529034,  3.17033031],
       [ 3.85061038,  4.17916616, 10.32104309,  4.82858143,  3.83668477]])

In [16]:
np.random.randint(0,5, (3,5)) #(3,5) lik ve elemanları 0 ile 5 arasında olacak matris üretir.

array([[1, 2, 2, 2, 4],
       [1, 3, 1, 4, 3],
       [4, 2, 1, 0, 0]])

## NumPy Özellikleri
* ndim: boyut sayısı
* shape: boyut bilgisi
* size: eleman sayısı
* dtype: veri tipi

Markdown'da maddeler yazmak için satırın başına (*) koymak yeterlidir.

In [1]:
import numpy as np

In [2]:
np.random.randint(10, size = 5) #başlangıç değeri belirtmediğimiz için otomatik kendisi değer alır (0). Yazdığımız kod; 5 elemanlı 0-10 arasında random vektör oluşturur.

array([5, 6, 0, 4, 8])

In [3]:
a = np.random.randint(10, size = 5)

In [4]:
a.ndim #tek boyutlu bir array olduğu için 1 sonucunu döndürecektir.

1

In [6]:
a.shape #tek boyutlu olduğu için (5,) çıktısını döndürecektir.

(5,)

In [7]:
a.size #arraydeki eleman sayısını -> 5'i döndürecektir.

5

In [9]:
a.dtype #array'in veri tipini yani int32 sonucunu döndürür.

dtype('int32')

## Yeniden Şekillendirme (reshaping)

In [11]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Problemlerimizi çözmek için bazen tek boyutlu dizilerin boyutlarını değiştirerek işlemlerimizi devam ettirmemiz gerekebilir, bu durumlarda da
reshape komutu bizlerin ihtiyacı olan komuttur.

In [12]:
b = a.reshape((3,3))
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

a array'i tek boyutlu bir arraydir. a array'indeki bilgileri yine tek bir sütunda tutsak fakat array'imiz çok boyutlu olsa olur mu? 

In [16]:
c = a.reshape((1,9))
c

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [17]:
c.ndim

2

In [18]:
a.ndim

1

a ve c array'leri aynı bilgileri tutmalarına rağmen boyutları farklıdır. Bazı problemleri çözerken çok boyutlu array'ler ile çalışıyorsak bu dönüştürme ile
işlerimizi daha rahat halledebiliyor olacağız.

## Array Birleştirme (Concatenation)

In [19]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [20]:
z = np.concatenate([x, y])
z

array([1, 2, 3, 4, 5, 6])

İki boyutlu array'^lerde concatenation işlemi yapmak için ise; 

In [21]:
a = np.array([[1,2,3],
             [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
b = np.concatenate([a, a])
b

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

Yukarıdaki concatenation işleminde otomatik olarak satıra göre işlem yapıldı, fakat biz satır değilde sütunlar için concatenation işlemi yapmak istersek
concatenate komutunu kullanırken **axis** değeri belirtmemiz gerekiyor. **axis** değeri **0** ise **satır**, **1** ise **sütun** bazlı concatenation işlemi 
yapılır. Komutu yazarken **axis** değeri **belirtilmezse default** olarak **0** değerini alır.

In [24]:
c = np.concatenate([a, a], axis = 1)
c

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## Array Ayırma (Splitting)

In [27]:
a = np.array([1, 5, 9, 3, 6, 8, 2, 1, 7])
a

array([1, 5, 9, 3, 6, 8, 2, 1, 7])

In [31]:
b = np.split(a, [2, 5])
b

[array([1, 5]), array([9, 3, 6]), array([8, 2, 1, 7])]

Yukarıdaki kod satırı ile yapılanlar; ilk parametre hangi array üzerinde işlem yapılacağını belirtmek için yazılır, ikinci parametre ise ayırma işleminin
nasıl olacağını belirtmek için yapılır. a array'ini 2. ve 5. indislerinde böl demiş olduk.

Peki bu ayırdığımız array'leri nasıl farklı değişkenler içerisinde tutarız?

In [32]:
x,y,z = np.split(a, [2, 5])

In [33]:
x

array([1, 5])

In [34]:
y

array([9, 3, 6])

In [35]:
z

array([8, 2, 1, 7])

## İki Boyutlu Ayırma

In [37]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Yukarıdaki çok boyutlu array'i 3. satırdam sonrasını ayırarak dikey olarak eklemek istersek;

In [50]:
alt, ust = np.vsplit(m, [3])

In [51]:
alt

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
ust

array([[12, 13, 14, 15]])

In [53]:
sag, sol = np.hsplit(m, [2])

In [54]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [55]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

## Array Sıralama (Sorting)

In [57]:
a = np.array([1, 3, 5, 7, 9, 6, 2])
a

array([1, 3, 5, 7, 9, 6, 2])

In [59]:
b = np.sort(a)
b

array([1, 2, 3, 5, 6, 7, 9])

Eğer ki np.sort fonksiyonu yerine a.sort methodunu kullanmış olsaydık kalıcı değişiklik yapmış olurduk. np.sort işleminin kalıcı olmasını istiyorsak bir 
değişkene atama yapmak zorundayız fakat direkt olarak sort methodunu kullanırsak var olan array'in içeriğinde oynama yapmış oluruz.

## İki Boyutlu Sıralama

sort'u kullanırken yine axis değerlerine ihtiyaç duyuyoruz. 1'e göre sıralama yapmasını istersek satırları, 0'a göre sıralama yapmasını istersek de 
sütunları kendi içerisinde sıralar.

In [62]:
a = np.random.normal(5, 10, (4,4)) #ortalaması 5, standart sapması 10 olan 4'e 4'lük array
a

array([[  9.42296682,  11.8251775 ,   0.81411613,   7.77501469],
       [  4.7627862 , -15.99379137,   4.06949454,   4.97454998],
       [ -6.48544507,  13.58149392,  15.84343955,   6.12668281],
       [ -3.88686353, -14.48000012,  -1.82101677,  -0.83502653]])

In [63]:
satir = np.sort(a, axis = 1)
satir

array([[  0.81411613,   7.77501469,   9.42296682,  11.8251775 ],
       [-15.99379137,   4.06949454,   4.7627862 ,   4.97454998],
       [ -6.48544507,   6.12668281,  13.58149392,  15.84343955],
       [-14.48000012,  -3.88686353,  -1.82101677,  -0.83502653]])

In [64]:
sutun = np.sort(a, axis = 0)
sutun

array([[ -6.48544507, -15.99379137,  -1.82101677,  -0.83502653],
       [ -3.88686353, -14.48000012,   0.81411613,   4.97454998],
       [  4.7627862 ,  11.8251775 ,   4.06949454,   6.12668281],
       [  9.42296682,  13.58149392,  15.84343955,   7.77501469]])

## Index ile Elemanlara Erişmek

In [65]:
a = np.random.randint(10, size = (3,4))
a

array([[5, 7, 6, 2],
       [3, 8, 4, 3],
       [2, 0, 2, 2]])

In [67]:
a[2, 3]

2

In [68]:
a[2, 3] = 8
a

array([[5, 7, 6, 2],
       [3, 8, 4, 3],
       [2, 0, 2, 8]])

**ÖNEMLİ NOT:** Eğer ki bir array oluştururken ondalıklı ifade kullanarak oluşturursak tüm array float tipinde olur fakat int türünde var olan bir 
    array'a float değerli bir eleman eklemek istersek o elemanın tam kısmını alarak array'in tipinde değişikliğe gitmez.

In [69]:
#Örneğin
a[2,2] = 3.4
a

array([[5, 7, 6, 2],
       [3, 8, 4, 3],
       [2, 0, 3, 8]])