# Ana başlık tek diyez (#) (Hücreyi seçerek JupyterLab görev çubuğunun sonunda bulunan alanda Markdown'ı seçmeliyiz.)

## Alt başlık iki diyez (##) (Hücreyi seçerek JupyterLab görev çubuğunun sonunda bulunan alanda Markdown'ı seçmeliyiz.)

_italik_ (_ xxx _ formatında yazarak italik formatta yazı yazabiliriz.)


**kalın** (* * xxx * *) formatında yazarak kalın formatta yazı yazabiliriz.)

# Neden Numpy ?

In [2]:
a = [1,2,3]
b = [4,5,6]
a
b

[4, 5, 6]

Hücreleme mantığından dolayı en alt satırda hangi eleman varsa JupyterLav çalıştırmak için onu seçer. a ve b'nin her ikisini de çalıştırmak istiyorsak ayrı ayrı hücrelerde çağırmalıyız.

In [3]:
a = [1,2,3]
b = [4,5,6]

In [4]:
ab = []
for i in range(0, len(a)):
    ab.append(a[i] * b[i])
ab

[4, 10, 18]

Yukarıdaki kod satırları numpy kütüphanesi kullanmadan iki vektörü çarpmak için gerekli olan işlemlerin bütünüdür, peki numpy ile ne yapmak gerekiyor.

In [1]:
import numpy as np #numpy kütüphanesini kullanmak için import ediyoruz.

In [7]:
a = np.array([1,2,3])
b = np.array([4,5,6])
#numpy array'leri oluşturmuş olduk.

In [8]:
a * b

array([ 4, 10, 18])

numpy'ı import ettikten sonra tek bir satır kod yazarak aynı sonucu alabiliyoruz.

Numpy ile daha üst seviyeden daha az efor ile daha fazla iş yapılabilir.

Veri saklama anlamında da numpy çok daha işimize yarıyor; liste ile farkına bakacak olursak 4 elemanlı bir liste ve np.array düşünelim. listede her bir eleman için
ayrı ayrı tip bilgisi tutulacaktır fakat np.array kullanarak bu sayıyı 1'e indirebiliyoruz.

In [2]:
np.array([1, 2, 3, 4.55], dtype="int")

array([1, 2, 3, 4])

In [3]:
np.array([1, 2, 3, 4.55])

array([1.  , 2.  , 3.  , 4.55])

Eğer ki array'i yazdıktan sonra dtype belirtmemiş olsaydık array'in tipi otomatik olarak float'a dönüşecekti fakat bazı durumlarda bunu istemeyebiliriz bu gibi durumlar için de array'i
oluştururken "dtype" özelliğinden faydanalarak içerisindeki verilerin hangi tipte olması gerektiğini belirleyebiliriz.

In [5]:
np.zeros(10) #0'lardan array oluşturur. #int'e çevirmek için dtype ekleyebilirsiniz.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones((3,5), dtype = int) #1'lerden array oluşturur.

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
np.full((2,3), 5, dtype = int) #Belirttiğimiz sayıya göre array oluşturur.

array([[5, 5, 5],
       [5, 5, 5]])

In [11]:
np.arange(0, 30, 5) #Belirtilen aralıkta 5'er artarak vektör üretir.

array([ 0,  5, 10, 15, 20, 25])

In [12]:
np.linspace(0, 1, 5) #0 ile 1 arasında eşit aralıklarda 5 adet eleman olacak şekilde vektör üretir.

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
np.random.normal(5, 3, (2,5)) #(2,5) lik ortalaması 5, standart sapması 3 olacak şekilde matris üretir. 

array([[ 6.56912866,  5.1207907 ,  5.4263912 , 11.55529034,  3.17033031],
       [ 3.85061038,  4.17916616, 10.32104309,  4.82858143,  3.83668477]])

In [16]:
np.random.randint(0,5, (3,5)) #(3,5) lik ve elemanları 0 ile 5 arasında olacak matris üretir.

array([[1, 2, 2, 2, 4],
       [1, 3, 1, 4, 3],
       [4, 2, 1, 0, 0]])