# Ana başlık tek diyez (#) (Hücreyi seçerek JupyterLab görev çubuğunun sonunda bulunan alanda Markdown'ı seçmeliyiz.)

## Alt başlık iki diyez (##) (Hücreyi seçerek JupyterLab görev çubuğunun sonunda bulunan alanda Markdown'ı seçmeliyiz.)

_italik_ (_ xxx _ formatında yazarak italik formatta yazı yazabiliriz.)


**kalın** (* * xxx * *) formatında yazarak kalın formatta yazı yazabiliriz.)

# Neden Numpy ?

In [2]:
a = [1,2,3]
b = [4,5,6]
a
b

[4, 5, 6]

Hücreleme mantığından dolayı en alt satırda hangi eleman varsa JupyterLav çalıştırmak için onu seçer. a ve b'nin her ikisini de çalıştırmak istiyorsak ayrı ayrı hücrelerde çağırmalıyız.

In [3]:
a = [1,2,3]
b = [4,5,6]

In [4]:
ab = []
for i in range(0, len(a)):
    ab.append(a[i] * b[i])
ab

[4, 10, 18]

Yukarıdaki kod satırları numpy kütüphanesi kullanmadan iki vektörü çarpmak için gerekli olan işlemlerin bütünüdür, peki numpy ile ne yapmak gerekiyor.

In [1]:
import numpy as np #numpy kütüphanesini kullanmak için import ediyoruz.

In [7]:
a = np.array([1,2,3])
b = np.array([4,5,6])
#numpy array'leri oluşturmuş olduk.

In [8]:
a * b

array([ 4, 10, 18])

numpy'ı import ettikten sonra tek bir satır kod yazarak aynı sonucu alabiliyoruz.

Numpy ile daha üst seviyeden daha az efor ile daha fazla iş yapılabilir.

Veri saklama anlamında da numpy çok daha işimize yarıyor; liste ile farkına bakacak olursak 4 elemanlı bir liste ve np.array düşünelim. listede her bir eleman için
ayrı ayrı tip bilgisi tutulacaktır fakat np.array kullanarak bu sayıyı 1'e indirebiliyoruz.

In [2]:
np.array([1, 2, 3, 4.55], dtype="int")

array([1, 2, 3, 4])

In [3]:
np.array([1, 2, 3, 4.55])

array([1.  , 2.  , 3.  , 4.55])

Eğer ki array'i yazdıktan sonra dtype belirtmemiş olsaydık array'in tipi otomatik olarak float'a dönüşecekti fakat bazı durumlarda bunu istemeyebiliriz bu gibi durumlar için de array'i
oluştururken "dtype" özelliğinden faydanalarak içerisindeki verilerin hangi tipte olması gerektiğini belirleyebiliriz.

In [5]:
np.zeros(10) #0'lardan array oluşturur. #int'e çevirmek için dtype ekleyebilirsiniz.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones((3,5), dtype = int) #1'lerden array oluşturur.

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
np.full((2,3), 5, dtype = int) #Belirttiğimiz sayıya göre array oluşturur.

array([[5, 5, 5],
       [5, 5, 5]])

In [11]:
np.arange(0, 30, 5) #Belirtilen aralıkta 5'er artarak vektör üretir.

array([ 0,  5, 10, 15, 20, 25])

In [12]:
np.linspace(0, 1, 5) #0 ile 1 arasında eşit aralıklarda 5 adet eleman olacak şekilde vektör üretir.

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
np.random.normal(5, 3, (2,5)) #(2,5) lik ortalaması 5, standart sapması 3 olacak şekilde matris üretir. 

array([[ 6.56912866,  5.1207907 ,  5.4263912 , 11.55529034,  3.17033031],
       [ 3.85061038,  4.17916616, 10.32104309,  4.82858143,  3.83668477]])

In [16]:
np.random.randint(0,5, (3,5)) #(3,5) lik ve elemanları 0 ile 5 arasında olacak matris üretir.

array([[1, 2, 2, 2, 4],
       [1, 3, 1, 4, 3],
       [4, 2, 1, 0, 0]])

## NumPy Özellikleri
* ndim: boyut sayısı
* shape: boyut bilgisi
* size: eleman sayısı
* dtype: veri tipi

Markdown'da maddeler yazmak için satırın başına (*) koymak yeterlidir.

In [1]:
import numpy as np

In [2]:
np.random.randint(10, size = 5) #başlangıç değeri belirtmediğimiz için otomatik kendisi değer alır (0). Yazdığımız kod; 5 elemanlı 0-10 arasında random vektör oluşturur.

array([5, 6, 0, 4, 8])

In [3]:
a = np.random.randint(10, size = 5)

In [4]:
a.ndim #tek boyutlu bir array olduğu için 1 sonucunu döndürecektir.

1

In [6]:
a.shape #tek boyutlu olduğu için (5,) çıktısını döndürecektir.

(5,)

In [7]:
a.size #arraydeki eleman sayısını -> 5'i döndürecektir.

5

In [9]:
a.dtype #array'in veri tipini yani int32 sonucunu döndürür.

dtype('int32')

## Yeniden Şekillendirme (reshaping)

In [11]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Problemlerimizi çözmek için bazen tek boyutlu dizilerin boyutlarını değiştirerek işlemlerimizi devam ettirmemiz gerekebilir, bu durumlarda da
reshape komutu bizlerin ihtiyacı olan komuttur.

In [12]:
b = a.reshape((3,3))
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

a array'i tek boyutlu bir arraydir. a array'indeki bilgileri yine tek bir sütunda tutsak fakat array'imiz çok boyutlu olsa olur mu? 

In [16]:
c = a.reshape((1,9))
c

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [17]:
c.ndim

2

In [18]:
a.ndim

1

a ve c array'leri aynı bilgileri tutmalarına rağmen boyutları farklıdır. Bazı problemleri çözerken çok boyutlu array'ler ile çalışıyorsak bu dönüştürme ile
işlerimizi daha rahat halledebiliyor olacağız.

## Array Birleştirme (Concatenation)

In [19]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [20]:
z = np.concatenate([x, y])
z

array([1, 2, 3, 4, 5, 6])

İki boyutlu array'^lerde concatenation işlemi yapmak için ise; 

In [21]:
a = np.array([[1,2,3],
             [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
b = np.concatenate([a, a])
b

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

Yukarıdaki concatenation işleminde otomatik olarak satıra göre işlem yapıldı, fakat biz satır değilde sütunlar için concatenation işlemi yapmak istersek
concatenate komutunu kullanırken **axis** değeri belirtmemiz gerekiyor. **axis** değeri **0** ise **satır**, **1** ise **sütun** bazlı concatenation işlemi 
yapılır. Komutu yazarken **axis** değeri **belirtilmezse default** olarak **0** değerini alır.

In [24]:
c = np.concatenate([a, a], axis = 1)
c

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## Array Ayırma (Splitting)

In [27]:
a = np.array([1, 5, 9, 3, 6, 8, 2, 1, 7])
a

array([1, 5, 9, 3, 6, 8, 2, 1, 7])

In [31]:
b = np.split(a, [2, 5])
b

[array([1, 5]), array([9, 3, 6]), array([8, 2, 1, 7])]

Yukarıdaki kod satırı ile yapılanlar; ilk parametre hangi array üzerinde işlem yapılacağını belirtmek için yazılır, ikinci parametre ise ayırma işleminin
nasıl olacağını belirtmek için yapılır. a array'ini 2. ve 5. indislerinde böl demiş olduk.

Peki bu ayırdığımız array'leri nasıl farklı değişkenler içerisinde tutarız?

In [32]:
x,y,z = np.split(a, [2, 5])

In [33]:
x

array([1, 5])

In [34]:
y

array([9, 3, 6])

In [35]:
z

array([8, 2, 1, 7])

## İki Boyutlu Ayırma

In [37]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Yukarıdaki çok boyutlu array'i 3. satırdam sonrasını ayırarak dikey olarak eklemek istersek;

In [50]:
alt, ust = np.vsplit(m, [3])

In [51]:
alt

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
ust

array([[12, 13, 14, 15]])

In [53]:
sag, sol = np.hsplit(m, [2])

In [54]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [55]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

## Array Sıralama (Sorting)

In [57]:
a = np.array([1, 3, 5, 7, 9, 6, 2])
a

array([1, 3, 5, 7, 9, 6, 2])

In [59]:
b = np.sort(a)
b

array([1, 2, 3, 5, 6, 7, 9])

Eğer ki np.sort fonksiyonu yerine a.sort methodunu kullanmış olsaydık kalıcı değişiklik yapmış olurduk. np.sort işleminin kalıcı olmasını istiyorsak bir 
değişkene atama yapmak zorundayız fakat direkt olarak sort methodunu kullanırsak var olan array'in içeriğinde oynama yapmış oluruz.

## İki Boyutlu Sıralama

sort'u kullanırken yine axis değerlerine ihtiyaç duyuyoruz. 1'e göre sıralama yapmasını istersek satırları, 0'a göre sıralama yapmasını istersek de 
sütunları kendi içerisinde sıralar.

In [62]:
a = np.random.normal(5, 10, (4,4)) #ortalaması 5, standart sapması 10 olan 4'e 4'lük array
a

array([[  9.42296682,  11.8251775 ,   0.81411613,   7.77501469],
       [  4.7627862 , -15.99379137,   4.06949454,   4.97454998],
       [ -6.48544507,  13.58149392,  15.84343955,   6.12668281],
       [ -3.88686353, -14.48000012,  -1.82101677,  -0.83502653]])

In [63]:
satir = np.sort(a, axis = 1)
satir

array([[  0.81411613,   7.77501469,   9.42296682,  11.8251775 ],
       [-15.99379137,   4.06949454,   4.7627862 ,   4.97454998],
       [ -6.48544507,   6.12668281,  13.58149392,  15.84343955],
       [-14.48000012,  -3.88686353,  -1.82101677,  -0.83502653]])

In [64]:
sutun = np.sort(a, axis = 0)
sutun

array([[ -6.48544507, -15.99379137,  -1.82101677,  -0.83502653],
       [ -3.88686353, -14.48000012,   0.81411613,   4.97454998],
       [  4.7627862 ,  11.8251775 ,   4.06949454,   6.12668281],
       [  9.42296682,  13.58149392,  15.84343955,   7.77501469]])

## Index ile Elemanlara Erişmek

In [65]:
a = np.random.randint(10, size = (3,4))
a

array([[5, 7, 6, 2],
       [3, 8, 4, 3],
       [2, 0, 2, 2]])

In [67]:
a[2, 3]

2

In [68]:
a[2, 3] = 8
a

array([[5, 7, 6, 2],
       [3, 8, 4, 3],
       [2, 0, 2, 8]])

**ÖNEMLİ NOT:** Eğer ki bir array oluştururken ondalıklı ifade kullanarak oluşturursak tüm array float tipinde olur fakat int türünde var olan bir 
    array'a float değerli bir eleman eklemek istersek o elemanın tam kısmını alarak array'in tipinde değişikliğe gitmez.

In [69]:
#Örneğin
a[2,2] = 3.4
a

array([[5, 7, 6, 2],
       [3, 8, 4, 3],
       [2, 0, 3, 8]])

## Array alt kümelere erişmek (Slicing ile elemanlara erişemek)

In [2]:
import numpy as np

In [3]:
a = np.arange(20, 30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [5]:
a[0:4]

array([20, 21, 22, 23])

In [7]:
a[2:]

array([22, 23, 24, 25, 26, 27, 28, 29])

In [8]:
a[1::2] #1. indisten başlayarak ikişer atlayarak elemanları yazdırmak için

array([21, 23, 25, 27, 29])

## İki boyutlu slice işlemleri

In [9]:
m = np.random.randint(5, 10, size = (5, 5))
m

array([[7, 9, 7, 6, 5],
       [5, 6, 9, 5, 5],
       [5, 9, 8, 7, 6],
       [7, 8, 5, 9, 8],
       [6, 7, 7, 5, 8]])

In [11]:
m[1,:] #1. satırdaki tüm sütunları listele (index olarak 1)

array([5, 6, 9, 5, 5])

In [12]:
m[2:4, 1:3] #2den 4'e kadar olan satırları ve 1'den 3'e kadar olan sütunları yazdırmak için

array([[9, 8],
       [8, 5]])

## Alt küme üzerinde işlem yapmak

In [13]:
a = np.random.randint(3, 10, size = (4, 4))
a

array([[8, 6, 5, 3],
       [9, 9, 9, 3],
       [4, 8, 5, 4],
       [8, 5, 9, 8]])

Normalde bir alt kümeyi değişken içerisine atarsak ve o alt kümede değişiklik yaparsak ana array'de bu değişiklikten etkilenir, bu durum bazı problemlerde işimize gelse de
bazı problemlerde de istemedğimiz bir durum olabiliyor. Alt kümede yaptığımız değişiklik ana array'i etkilemesin istersek;

In [15]:
alt_a = a[1:3, 0:2] #1'den 3'e kadar olan satırları ve 0'dan 2'ye kadar olan satırları almış olduk.
alt_a

array([[9, 9],
       [4, 8]])

In [16]:
alt_a[0, 0] = 5 # bu işlemi yaptıktan sonra hem alt kümede hem de ana array'de değişiklik olmuş oluyor.
alt_a

array([[5, 9],
       [4, 8]])

In [17]:
a

array([[8, 6, 5, 3],
       [5, 9, 9, 3],
       [4, 8, 5, 4],
       [8, 5, 9, 8]])

Peki sadece alt kümede değişiklik olsun istersek?;

In [20]:
alt_b = a[1:3, 0:2].copy() #copy komutunu ekleyerek ana array'den bağımsız olarak işlemler yapabiliriz.
alt_b

array([[5, 9],
       [4, 8]])

In [21]:
alt_b[0,0] = 7
alt_b

array([[7, 9],
       [4, 8]])

In [22]:
a

array([[8, 6, 5, 3],
       [5, 9, 9, 3],
       [4, 8, 5, 4],
       [8, 5, 9, 8]])

Yukarıda da görüldüğü gibi alt kümede [0, 0] da 5 yerine 7 yazdık fakat bu sadece alt kümedeki değeri değiştirmiş oldu ana array'de her şey eskisi gibi duruyor.

## Fancy Index ile elemanlara erişmek

In [23]:
v = np.arange(0, 30, 3) #0'dan 30'a kadar 3'er olarak atlayarak array oluştur
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

Normalde v array'inin 1. 3. ve 5. indekslerine erişmek istiyor olsaydık ayrı ayrı yazarak bu erişimi sağlayacaktık, yani;

In [24]:
v[1]

3

In [27]:
v[3]

9

In [28]:
v[5]

15

Bu indeksleri tek bir arada görmek istiyor olsaydık ise; 

In [29]:
[v[1], v[3], v[5]]

[3, 9, 15]

Çok büyük indeksli array'lerde bu işlemler ile uğraşmak yerine fancy index kullanılır;

In [30]:
al_getir = [1, 3, 5]
al_getir

[1, 3, 5]

In [31]:
v[al_getir]

array([ 3,  9, 15])

## İki boyutta fancy index

In [66]:
v = np.arange(0, 16).reshape((4,4)) #0'dan 16'ya kadar 4,4'lük array oluştur
v

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

1 ve 6 elemanlarını göstermek istersek;

In [64]:
satir = np.array([0, 1])
sutun = np.array([1, 2])

In [67]:
v[satir, sutun]

array([1, 6])

## Basit index ile Fancy index

In [68]:
v

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [71]:
v[1, [2,3]] #1. satırdaki 2. ve 3. sütundaki elemanları çağırmış olduk. Bunu yaparkende basit index ve fancy indexi aynı anda kullanmış olduk.

array([6, 7])

## slice ile fancy

In [73]:
v[1:, [0,2]] #1. satırın 0 ve 2. sütunlarının tüm elemanlarını listelemek için;

array([[ 4,  6],
       [ 8, 10],
       [12, 14]])

## Koşullu eleman işlemleri

In [74]:
v = np.array([1, 3, 5, 7, 9, 11])
v

array([ 1,  3,  5,  7,  9, 11])

In [75]:
v > 5 # v vektöründeki tüm elemanları tek tek sorgular 5'ten büyük olanlar için true küçük olanlar için false değerini döndürür.

array([False, False, False,  True,  True,  True])

In [76]:
v[v > 5] # 5'ten büyük olan değerleri array şeklinde göstermemiz için;

array([ 7,  9, 11])

In [77]:
v [v == 5] # değeri 5'e eşit olanlar listelenir.

array([5])

In [78]:
v[v != 5] #değeri 5'e eşit olmayanları listeleyerek döndürür.

array([ 1,  3,  7,  9, 11])

In [83]:
v / 10 * 2 #tüm elemanları 10 a böldükten sonra 2 ile çarpıp listelemek için;

array([0.2, 0.6, 1. , 1.4, 1.8, 2.2])

## Matematiksel İşlemler

In [84]:
v = np.array([2, 4, 6, 8, 3, 5, 7])
v

array([2, 4, 6, 8, 3, 5, 7])

In [85]:
v - 1 #tüm elemanlardan 1 çıkararak listeler;

array([1, 3, 5, 7, 2, 4, 6])

## ufunc işlemleri

In [86]:
np.subtract(v, 1) #numpy'ın içerisinden subtract işlemi gelsin ve v üzerinde tüm elemanlardan 1 çıkarma işlemi yapıp listelesin;

array([1, 3, 5, 7, 2, 4, 6])

In [88]:
np.add(v, 3) #numpy'ın içerisinden add işlemi gelsin ve v üzerinde tüm elemanlara 3 ekleme işlemi yapıp listelesin;

array([ 5,  7,  9, 11,  6,  8, 10])

In [89]:
np.multiply(v, 2) #numpy'ın içerisinden multiply işlemi gelsin ve v üzerinde tüm elemanları 2 ile çarpma iişlemi yapıp listelesin;

array([ 4,  8, 12, 16,  6, 10, 14])

In [90]:
np.divide(v, 10) #numpy'ın içerisinden divide işlemi gelsin ve v üzerinde tüm elemanları 10 ile bölme iişlemi yapıp listelesin;

array([0.2, 0.4, 0.6, 0.8, 0.3, 0.5, 0.7])

In [91]:
np.power(v, 2) #numpy'ın içerisinden power işlemi gelsin ve v üzerinde tüm elemanların karesini alma iişlemi yapıp listelesin;

array([ 4, 16, 36, 64,  9, 25, 49], dtype=int32)

In [93]:
np.mod(v, 3) #numpy'ın içerisinden mod işlemi gelsin ve v üzerinde tüm elemanların 3'e bölümünden kalanı kaç olduğunu listelesin;

array([2, 1, 0, 2, 0, 2, 1], dtype=int32)

In [94]:
np.absolute(np.array([-5])) #mutlak değer almak için

array([5])

In [96]:
[[np.sin(360)], [np.cos(180)]] #trigonametrik ifadeler

[[0.9589157234143065], [-0.5984600690578581]]

In [97]:
v = np.array([1, 5, 7, 6])
np.log(v) # v array'inin elemanlarının logaritmasını alıp listeler

array([0.        , 1.60943791, 1.94591015, 1.79175947])

In [98]:
v = np.array([1, 5, 7, 6])
np.log2(v) # v array'inin elemanlarının 2 tabanında logaritmasını alıp listeler

array([0.        , 2.32192809, 2.80735492, 2.5849625 ])

## İki bilinmeyenli denklem çözümü

5 * x0 + x1 = 12

x0 + 3 * x1 = 10

In [99]:
a = np.array([[5, 1], [1, 3]]) #5 değeri ilk satırdaki x0'ın katsayısı, 1 ise ilk satırdaki x1'in katsayısı. ikinci 1 ise ikinci satıdaki ilk bilinmeyenin katsayısı, 3 ise ikinci satırdaki ikinci bilinmeyenin katsayısı

In [100]:
a

array([[5, 1],
       [1, 3]])

In [102]:
b = np.array([12, 10]) #satırlara karşılık gelen sonuç değerleri
b

array([12, 10])

In [103]:
x = np.linalg.solve(a, b) # bu verdiğimiz bilgilerden faydalanarak x0 ve x1'in değerlerini bulur.
x

array([1.85714286, 2.71428571])